
ALTER SESSION SET nls_date_format = "mm/dd/yyyy hh24:mi:ss";

set sqlprompt "_USER'@'_CONNECT_IDENTIFIER > ";

SET TIMING ON
SET SERVEROUTPUT ON
SET TERMOUT ON
SET PAGESIZE 24
SET LINESIZE 78


